### ISSUE TITLE
making an installer for windows

### ISSUE THREAD

**Issue by abdelouahabb** [ajdavis/mongo-python-driver#7]
hit
pymongo has C extension that speeds the driver, and the user must install visual studio, mingw  will not work, the official driver has the EXE installer, hope this one too.
thank you.

**Comment by ajdavis** [comment]
Hi, Windows isn't officially supported by Tornado:

https://groups.google.com/d/msg/python-tornado/Yf2b8ryih18/Xtog-1YGq4gJ

.... so I won't make any effort to test or deploy Motor on Windows.

Install easy_install on Windows:

http://pypi.python.org/pypi/setuptools#windows

Then 'easy_install pip', then 'pip install tornado greenlet git+https://github.com/ajdavis/mongo-python-driver.git@motor'

**Comment by abdelouahabb** [comment]
ok thank you :)
but the problem is compiling the C extension
BTW: tornado works great in windows, it just uses SELECT instead of epoll() or kqueue()

**Comment by ajdavis** [comment]
Motor has no special C extensions, it uses the same C extensions as PyMongo does. You can get those compiled for Windows from the exe's here: http://pypi.python.org/pypi/pymongo/

**Comment by abdelouahabb** [comment]
ah so i can directy add the directories to the latest pymongo! because i dont remembe on day i saw that it is avoided to use pymongo and then use motor...dont remember where.
thank you again :)
